  @extends('master')

  @section('content')
    <div class="container">
      <div class="fancybox-container fancybox-show-controls fancybox-show-infobar fancybox-show-buttons fancybox-show-caption fancybox-container--ready fancybox-controls--canzoomIn" role="dialog" tabindex="-1" id="fancybox-container-2" style=""><div class="fancybox-bg" style="transition-duration: 330ms;"></div><div class="fancybox-controls"><div class="fancybox-infobar"><button data-fancybox-previous="" class="fancybox-button fancybox-button--left" title="Previous"></button><div class="fancybox-infobar__body"><span class="js-fancybox-index">1</span>&nbsp;/&nbsp;<span class="js-fancybox-count">28</span></div><button data-fancybox-next="" class="fancybox-button fancybox-button--right" title="Next"></button></div><div class="fancybox-buttons"><button data-fancybox-close="" class="fancybox-button fancybox-button--close" title="Close (Esc)"></button><button data-fancybox-play="" class="fancybox-button fancybox-button--play" title="Slideshow (P)"></button><button data-fancybox-fullscreen="" class="fancybox-button fancybox-button--fullscreen" title="Full screen (F)"></button><button data-fancybox-thumbs="" class="fancybox-button fancybox-button--thumbs" title="Thumbnails (G)"></button></div></div><div class="fancybox-slider-wrap"><div class="fancybox-slider" style="transform: translate(0px, 0px);"><div class="fancybox-slide fancybox-slide--current fancybox-slide--image fancybox-slide--complete" style="transform: translate(0px, 0px);"><div class="fancybox-placeholder" style="transform: translate(0px, 76px); width: 1371px; height: 785px; opacity: 1;"><img class="fancybox-image" src="/public/images/2018/sofa_out.jpg"></div></div><div class="fancybox-slide fancybox-slide--image" style="transform: translate(-1401px, 0px);"><div class="fancybox-placeholder" style="transform: translate(39px, 44px); width: 1293px; height: 850px;"><img class="fancybox-image" src="/public/images/2000/ste_bath_1.jpg"></div></div><div class="fancybox-slide fancybox-slide--image" style="transform: translate(1401px, 0px);"><div class="fancybox-placeholder" style="transform: translate(0px, 84px); width: 1371px; height: 770px;"><img class="fancybox-image" src="/public/images/2018/mids_dinner.JPG"></div></div></div></div><div class="fancybox-caption-wrap"><div class="fancybox-caption"><strong>Överlöpe</strong><br>Alvar, Jakob, Vilma och Idun<br>2018-08-18</div></div></div>
    </div>
        
    <!-- ------------- scripts --------------------------------------- -->  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  @endsection
